# Generated by Django 6.0.4 on 2026-07-06 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], max_length=20)),
                ('refill_date', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_station', models.CharField(max_length=150)),
                ('mileage', models.PositiveIntegerField(help_text='Vehicle mileage during refill (km)')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-refill_date', '-created_at'],
            },
        ),
    ]
