# Generated by Django 6.0.4 on 2026-07-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('Mini Bus', 'Mini Bus'), ('Standard Bus', 'Standard Bus'), ('VIP Coach', 'VIP Coach')], max_length=30)),
                ('seat_capacity', models.PositiveIntegerField()),
                ('manufacture_year', models.PositiveIntegerField()),
                ('insurance_expiry', models.DateField()),
                ('road_tax_expiry', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
