# Generated by Django 6.0.4 on 2026-07-05 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('Oil Change', 'Oil Change'), ('Engine Service', 'Engine Service'), ('Brake Service', 'Brake Service'), ('Tyre Replacement', 'Tyre Replacement'), ('Air Conditioning', 'Air Conditioning'), ('Battery Replacement', 'Battery Replacement'), ('General Inspection', 'General Inspection'), ('Other', 'Other')], max_length=50)),
                ('workshop', models.CharField(max_length=150)),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(help_text='Vehicle mileage (km)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
