# Generated by Django 6.0.4 on 2026-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenance_needs_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='needs_maintenance',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Used for AI model training', max_length=3),
        ),
    ]
