# Generated by Django 6.0.4 on 2026-07-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Smart Bus Management System', max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=30)),
                ('company_address', models.TextField(blank=True)),
                ('currency', models.CharField(default='RM', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kuala_Lumpur', max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('minimum_training_records', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
