# Generated by Django 6.0.4 on 2026-09-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('bookings', '0002_alter_booking_customer'),
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
